### ISSUE TITLE
Users.csv outdated 

### ISSUE THREAD

**Issue by baxterdmutt** [DMR-Database/database-beta#10]
I’ve been posting in the wrong place it seems. Sorry. 
Einstein has told me that the database is up to date and showed me that my info is correct but it’s not making it into the tools app. I had just run it yesterday and my current location is “Armstrong” and has been for over 2 years. But the address that the tools installed in my md390 is “Surrey” after the install of the users.csv yesterday. 
edit: I just ran the TyteraFlashTool and checked the userdb.bin and it’s wrong. It shows my very old location. 
![IMG_9165](https://github.com/DMR-Database/database-beta/assets/35186027/4854bfd8-361b-4760-be65-577066f2fe14)

**Comment by javastraat** [comment]
do you use the latest version of the tool ?
https://github.com/DMR-Database/database-tools

**Comment by baxterdmutt** [comment]
From 3 days ago.

**Comment by javastraat** [comment]
ok since you wont tell any more than i foto i guess you use the tyt tools
the database has no problems, it the tools programm,
it seems that it downloads the old version, we will closed this here and move to the tools section, so the programmer can fix this

this is not a db problem, you can still download the usr.bin and and use the tool to flash it thru open file

**Comment by baxterdmutt** [comment]
We’ll hang on. I was using the windows version.  But looking carefully that looks like it’s 4 years old. If I follow some of the links they are dead.  What am I supposed to use????

**Comment by baxterdmutt** [comment]
Ok. Sounds good

**Comment by javastraat** [comment]
i just downloaded (the 4 year old version, should be the normal one) and it downloads a db of 198xxx users. that is an old db for sure. so i  opend a issue with the maker of the tools to dubble check the download url in the program.
you can subscribe to https://github.com/DMR-Database/database-tools/issues/7 to get notified once pd1loi fixes it


gr PD2EMC
