### ISSUE TITLE
From where is this database generated?

### ISSUE THREAD

**Issue by slavik0329** [DMR-Database/database-beta#2]
Is there a script for generating an up-to-date version?

**Comment by javastraat** [comment]
The base user.bin file (md380/390) is created by kd4z tools with a little tlc on some scripts (https://github.com/KD4Z/md380tools-vm) every 30min. After running it will be converted by script to alle the other databases :)

**Comment by slavik0329** [comment]
I was looking through the source and it looks like the DMR id data is coming from:
http://www.dmr-marc.net/cgi-bin/trbo-database/datadump.cgi?table=users&format=csv&header=0

When I try to manually download that file, theres a 404 error.

**Comment by javastraat** [comment]
https://github.com/KD4Z/md380tools-vm/blob/master/addstatic is the file with the resources that we use and combine, then we cross reference them etc etc

**Comment by slavik0329** [comment]
Okay great, I see it now! I'm wondering then why my new callsign isn't showing up in the recent database-beta db. When I download from https://radioid.net/static/user.csv is has my latest info.

**Comment by javastraat** [comment]
ah ok 
i will look into that 
whats your call sign ?

what happens i think : our database supply's all missing data, the scripts thinks that your data is complete and dont touch the values, in our database :) i think :)

fixxable :)

**Comment by slavik0329** [comment]
My callsign is K2SAD. Original callsign was KD2TTY and it's still in the DB. 

Thanks so much for the help!

**Comment by javastraat** [comment]
so you just got a new callsign and the rest is the same ?

3165143,KD2TTY,Steve,New York,NY,,US

**Comment by slavik0329** [comment]
Yes, only the callsign is wrong.

**Comment by javastraat** [comment]
changed it and rerun all scripts, so it is changed in both databases :) 

can you confirm it is all ok on your end ?

**Comment by slavik0329** [comment]
Hey, I just checked and it looks like you put KD2SAD instead of K2SAD.

**Comment by javastraat** [comment]
sorry , fixed

**Comment by slavik0329** [comment]
Thank you! I can verify it's correct now
