### ISSUE TITLE
Error in database

### ISSUE THREAD

**Issue by ideal54** [DMR-Database/database-beta#3]
I have two DMR hotspots running side by side. One uses your database and the other uses the default Pi-star database.

I have recently noticed that sometimes, different call signs are being displayed on each hotspot for the same station. When this happens it is the pi-star default database that displays the correct call sign. 

e.g. For DMR ID: 5050456, your latest database (here) displays VK3FNQS. The Pi-Star database displays VK3NQS. The correct call sign is VK3NQS. This user probably had a recent call sign upgrade to remove the 'F' from their call sign that has resulted in a change to the database.

HOWEVER, if you look for VK3NQS in your most recent database it lists DMR ID: 5053091 which is incorrect.  If you look in the radioid.net database the correct call sign for DMR ID 5053091 is VK3DQS.

I expect there are others as I have noticed several differences over the last couple of days.

Regards
Ian

**Comment by PD1WP** [comment]
Hello Ian
I see you mean the beta and not the corrected version. I'm going to make a new one today that I'm correcting. Will see if the error is there when I'm done. I will particularly follow these IDs.
73
Wilfred PD1WP



-------- Oorspronkelijk bericht --------
Van: Ian <notifications@github.com>
Datum: 19-10-2020 05:18 (GMT+01:00)
Aan: DMR-Database/database-beta <database-beta@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Onderwerp: [DMR-Database/database-beta] Error in database (#3)


I have two DMR hotspots running side by side. One uses your database and the other uses the default Pi-star database.

I have recently noticed that sometimes, different call signs are being displayed on each hotspot for the same station. When this happens it is the pi-star default database that displays the correct call sign.

e.g. For DMR ID: 5050456, your latest database (here) displays VK3FNQS. The Pi-Star database displays VK3NQS. The correct call sign is VK3NQS. This user probably had a recent call sign upgrade to remove the 'F' from their call sign that has resulted in a change to the database.

HOWEVER, if you look for VK3NQS in your most recent database it lists DMR ID: 5053091 which is incorrect. If you look in the radioid.net database the correct call sign for DMR ID 5053091 is VK3DQS.

I expect there are others as I have noticed several differences over the last couple of days.

Regards
Ian
