### ISSUE TITLE
Database request for Pi-star’s “stripped.csv”...

### ISSUE THREAD

**Issue by M6XRM** [DMR-Database/database-beta#5]
Hi.
Is there any chance you be create and host an auto-generating database for the “stripped.csv” in pi-star along with your others?

The columns would need to be specific to feed the Nextion display fields correctly tho:

Column 1: DMR ID
Column 2: CALLSIGN
Column 3: FIRST NAME
Column 4: LAST NAME
Column 5: CITY
Column 6: STATE/PROV
Column 7: COUNTRY
Column 8: REMARKS

if you can’t, would you be prepared let me know how you auto-regenerate yours please?

Best 73...

Richie.

**Comment by PD1WP** [comment]
Hello Richie I have forwarded your e-mail to our specialist regarding the adaptation of the database for various radios and hotspots. 73Wilfred PD1W,DMR User Database Team 
-------- Oorspronkelijk bericht --------Van: M6XRM <notifications@github.com> Datum: 24-02-2021  22:00  (GMT+01:00) Aan: DMR-Database/database-beta <database-beta@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [DMR-Database/database-beta] Database request for Pi-star’s “stripped.csv”... (#5) 

Hi.

Is there any chance you be create and host an auto-generating database for the “stripped.csv” in pi-star along with your others?

The columns would need to be specific to feed the Nextion display fields correctly tho:

Column 1: DMR ID

Column 2: CALLSIGN

Column 3: FIRST NAME

Column 4: LAST NAME

Column 5: CITY

Column 6: STATE/PROV

Column 7: COUNTRY

Column 8: REMARKS

if you can’t, would you be prepared let me know how you auto-regenerate yours please?

Best 73...

Richie.

**Comment by M6XRM** [comment]
Thank you Wilfred…i appreciate it Sir! :)

Best 73…

Richie
M6XRM

tailgaters[dot]uk
richie[at]richiemills[dot]com
INSTAGRAM: richardmills
AMATEUR RADIO: M6XRM
